### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by nevits8as** [kingdomcreation/MultipleBootstrapModals#1]
I have a form inside the modal using your code, and i can get de ID of i wanna edit from one table fine; but when i edit one input of this form for update a value in database the submit button close the modal and leave a page in blank. Before i used your code i call the remote page inside a iframe and its works god, but i need to remove that iframe and for that i tray whit your option.

The SQL update a database its in a same .php were are the modal content

**Comment by kingdomcreation** [comment]
Please note that this is a jQuery and Bootstrap project. Im glad to say that Bootstrap has addressed the issue proposed by this project and the MultipleBootstrapModals is now officially supported by the framework to achieve the same effect. 

http://getbootstrap.com/javascript/#modals-related-target
